### ISSUE TITLE
Opera add-on

### ISSUE THREAD

**Issue by alexanderwallin** [spite/linkognito#1]
Hey! Love this thing. Love the name. Need it for Opera.

If you're not already doing it, I can Operafy it.

**Comment by spite** [comment]
Thanks!

I've installed the [Download Chrome Extension](https://addons.opera.com/en-gb/extensions/details/download-chrome-extension-9/?display=en) for Opera, and then installed Linkognito from the Chrome Store and it works.

Does that work for you?

**Comment by alexanderwallin** [comment]
Aha, didn't know about that one. Thanks for the tip!

It'd still be much nicer to have it in the Opera add-ons store, though. Do you think it will be much work maintaining both? I haven't made an Opera add-on myself.

**Comment by spite** [comment]
I've published the extension to Opera a few hours ago, it says it still has
to go through moderation. We'll have to wait...

**Comment by alexanderwallin** [comment]
I get `502 Bad Gateway` all over the add-ons site a.t.m., so I can't check.

**Comment by spite** [comment]
So after taking SEVEN days to review, i get this:

> Status has changed for Linkognito
> Linkognito v1.1 on Opera Current: Disapproved. Message from moderator:
> There is no icon in ext. manager (Ctrl + Shift + E).
> Code reviewed. Tested. No other issues.

Which is something they could have automatically checked when submitting the package.
I've updated the package and submitted again, but I won't pursue this process much longer

**Comment by spite** [comment]
Published! https://addons.opera.com/en-gb/extensions/details/linkognito/

**Comment by alexanderwallin** [comment]
Nice! I'm trying to figure out how to make room for it. Opera has occupied all three commands, where alt+click downloads what is at the link's URL.

**Comment by spite** [comment]
Yes, same binding for Chrome, but i seldom use it. I thought of adding hot keys combinations (Shift+Alt+click) but then if feels like it's harder than Right click + Open

**Comment by alexanderwallin** [comment]
Waaat, shift+alt+click works with Linkognito. Out of the box!
